### ISSUE TITLE
handle poloniex.PoloniexError: Connection timed out.

### ISSUE THREAD

**Issue by miti0** [miti0/mosquito#14]
Traceback (most recent call last):
  File "mosquito.py", line 23, in <module>
    parser.add_argument("--backtest", help="Simulate your strategy on history ticker data", action='store_true')
  File "mosquito.py", line 9, in main
    engine.run()
  File "/home/miro/dev/mosquito/core/engine.py", line 140, in run
    self.trades)
  File "/home/miro/dev/mosquito/core/bots/live.py", line 57, in trade
    return self.exchange.trade(actions, wallet, TradeMode.live)
  File "/home/miro/dev/mosquito/exchanges/exchange.py", line 68, in trade
    return self.exchange.trade(actions, wallet, trade_mode)
  File "/home/miro/dev/mosquito/exchanges/poloniex/polo.py", line 82, in trade
    actions = self.life_trade(actions)
  File "/home/miro/dev/mosquito/exchanges/poloniex/polo.py", line 97, in life_trade
    wallet = self.get_balances()
  File "/home/miro/dev/mosquito/exchanges/poloniex/polo.py", line 28, in get_balances
    balances = self.polo.returnBalances()
  File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 279, in returnBalances
    return self.__call__('returnBalances')
  File "/usr/local/lib/python3.5/dist-packages/poloniex/retry.py", line 15, in wrapped
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 175, in __call__
    return self.parseJson(ret.text)
  File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 197, in parseJson
    raise PoloniexError(jsonout['error'])
poloniex.PoloniexError: Connection timed out. Please try again.

**Comment by miti0** [comment]
fixed [7382863](https://github.com/miti0/mosquito/commit/73828639a3437dbef69dcb675b65ae7834b1d6a9)
