### ISSUE TITLE
poloniex: Invalid json response returned

### ISSUE THREAD

**Issue by crack00r** [miti0/mosquito#33]
Add Poloniex Failsafe

```
Starting simulation..
dataset_cnt: 1
Couldn't find exchange rate for: USDT
Couldn't find exchange rate for: USDT
Couldn't find exchange rate for: USDT
Thu Aug  3 12:47:28 2017, close:0.067000, | 0.00277929USDT| 0.03494554BTC | $: 0.0%, b&h: 0.0%
going to sleep for:  13  seconds.
dataset_cnt: 2
Couldn't find exchange rate for: USDT
Couldn't find exchange rate for: USDT
Thu Aug  3 12:48:29 2017, close:0.067000, | 0.00277929USDT| 0.03494554BTC | $: 0.0%, b&h: 0.0%
going to sleep for:  28  seconds.
dataset_cnt: 3
Couldn't find exchange rate for: USDT
Couldn't find exchange rate for: USDT
Thu Aug  3 12:49:27 2017, close:0.067000, | 0.00277929USDT| 0.03494554BTC | $: 0.0%, b&h: 0.0%
going to sleep for:  23  seconds.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 244, in handleReturned
    out = _loads(data, parse_float=str)
  File "/usr/lib/python3.5/json/__init__.py", line 332, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mosquito.py", line 35, in <module>
    main(args)
  File "mosquito.py", line 9, in main
    engine.run()
  File "/root/mosquito/core/engine.py", line 139, in run
    self.ticker = self.bot.get_next(self.interval)
  File "/root/mosquito/core/bots/live.py", line 37, in get_next
    df = self.exchange.get_symbol_ticker(pair)
  File "/root/mosquito/exchanges/exchange.py", line 35, in get_symbol_ticker
    return self.exchange.get_symbol_ticker(symbol)
  File "/root/mosquito/exchanges/poloniex/polo.py", line 41, in get_symbol_ticker
    ticker = self.polo.returnTicker()[symbol]
  File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 276, in returnTicker
    return self.__call__('returnTicker')
  File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 143, in retrying
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 218, in __call__
    return self.handleReturned(ret.text)
  File "/usr/local/lib/python3.5/dist-packages/poloniex/__init__.py", line 251, in handleReturned
    raise PoloniexError('Invalid json response returned')
poloniex.PoloniexError: Invalid json response returned
root@j314793:~/mosquito#

```

**Comment by miti0** [comment]
Thank you again for reporting this! Issue should be fixed now [ab79785](https://github.com/miti0/mosquito/commit/ab79785a6295d72600f4486485226681a62d7181)
