### ISSUE TITLE
Exception: inputs are all NaN

### ISSUE THREAD

**Issue by crack00r** [miti0/mosquito#36]
Got negative macd, skipping pair: BTC_BELA
macd_value: -1.08262108262e-09
signal_line: -2.67806267806e-09
rsi: 0.0
sma1: 4.66666666667e-07 sma2: 4.65e-07
ema1: 4.66666666667e-07 ema2: 4.65e-07
Traceback (most recent call last):
  File "mosquito.py", line 35, in <module>
    main(args)
  File "mosquito.py", line 9, in main
    engine.run()
  File "/root/mosquito/core/engine.py", line 158, in run
    self.actions = self.strategy.calculate(self.look_back, self.wallet)
  File "/root/mosquito/strategies/mosquito.py", line 88, in calculate
    macd_value, signal_line = macd(close, numpy.asarray(prev_pair_macds))
  File "/root/mosquito/lib/indicators/macd.py", line 23, in macd
    signal_line = talib.EMA(previous_macds[-signal_period:], timeperiod=signal_period)[-1]
  File "talib/func.pyx", line 7092, in talib.func.EMA (talib/func.c:79408)
Exception: inputs are all NaN
root@j314793:~/mosquito#

**Comment by miti0** [comment]
fixed [d20d5a7](https://github.com/miti0/mosquito/commit/d20d5a7d21f6a41ad76427a975b011d5951171bb)
