### ISSUE TITLE
get_price: got empty dataframe for pair: BTC_ETH

### ISSUE THREAD

**Issue by TheRoboKitten** [miti0/mosquito#47]
get_price: got empty dataframe for pair: BTC_ETH, skipping!
Could not find pairs ticker, skipping trade

I am not sure what this means, but I dont have ETH anywhere in my config lol

**Comment by miti0** [comment]
last commit switched from using config.ini to mosquito.ini. Please rename the mosquito.sample.ini to mosquito.ini and set the parameters to condi

Reason is that we changed to new argument and config parser. Now we can change all parameters with arguments.
...please can you check what you have in mosquito.ini file?

**Comment by TheRoboKitten** [comment]
Traceback (most recent call last):
  File "mosquito.py", line 35, in <module>
    main(args)
  File "mosquito.py", line 8, in main
    engine = Engine(args, 'config.ini')
  File "/home/cluster/Desktop/mosquito/core/engine.py", line 41, in __init__
    self.parse_config(config_file)
  File "/home/cluster/Desktop/mosquito/core/engine.py", line 99, in parse_config
    self.root_report_currency = config['Trade']['root_report_currency']
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'Trade'
