### ISSUE TITLE
backfill for bittrex --all ends with exception

### ISSUE THREAD

**Issue by miti0** [miti0/mosquito#54]
reproduce (run following for bittrex exchange):

`python3 backfill --days 5 --all`

error:
Getting currency data: BTC-ADT, days left: 2Got Timeout exception:HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=30)

! Got empty result for pair: BTC-ADT
 (got total candles: 0)
Getting currency data: BTC-ADT, days left: 1Traceback (most recent call last):
  File "/home/miro/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/miro/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/miro/anaconda3/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miro/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/miro/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/miro/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/miro/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/home/miro/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7ff60aad8c88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miro/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/miro/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/miro/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bittrex.com', port=443): Max retries exceeded with url: /api/v2.0/pub/market/getticks?marketName=BTC-ADT&tickInterval=fiveMin (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff60aad8c88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "backfill.py", line 103, in <module>
    main(options)
  File "backfill.py", line 66, in main
    candles = exchange.get_candles(pair, epoch_from, epoch_to, 300)  # by default 5 minutes candles (minimum)
  File "/home/miro/dev/mosquito/exchanges/bittrex/bittrexclient.py", line 67, in get_candles
    res = self.bittrex.get_ticks(currency_pair, 'fiveMin')
  File "/home/miro/anaconda3/lib/python3.6/site-packages/bittrex/bittrex.py", line 383, in get_ticks
    return self.api_query('market/getticks', {'marketName': market, 'tickInterval': tick_interval}, version='v2.0')
  File "/home/miro/anaconda3/lib/python3.6/site-packages/bittrex/bittrex.py", line 82, in api_query
    headers={"apisign": hmac.new(self.api_secret.encode(), request_url.encode(), hashlib.sha512).hexdigest()}
  File "/home/miro/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/miro/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/miro/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/miro/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/miro/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='bittrex.com', port=443): Max retries exceeded with url: /api/v2.0/pub/market/getticks?marketName=BTC-ADT&tickInterval=fiveMin (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff60aad8c88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

**Comment by miti0** [comment]
added exception handling [bc6510c](https://github.com/miti0/mosquito/commit/bc6510c0e4287aecbf44b739cb0231bd6e15c6f8)
